-d D:\my_fpga_project\SZU-A-major-project-on-computer-architecture-main\lab3\fpga\gowin_tang_nano_20k\impl\gwsynthesis\gowin_tang_nano_20k.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\my_fpga_project\SZU-A-major-project-on-computer-architecture-main\lab3\fpga\gowin_tang_nano_20k\src\gowin.cst
-cfg D:\my_fpga_project\SZU-A-major-project-on-computer-architecture-main\lab3\fpga\gowin_tang_nano_20k\impl\pnr\device.cfg
-sdc D:\my_fpga_project\SZU-A-major-project-on-computer-architecture-main\lab3\fpga\gowin_tang_nano_20k\src\gowin.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
